# Generated by Django 5.2 on 2025-07-28 09:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='active_work_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_description', models.CharField(max_length=255)),
                ('wo_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wo_status', models.CharField(max_length=50)),
                ('wo_created_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_number', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_completion', models.DateTimeField(blank=True, null=True)),
                ('actual_failure_date', models.DateTimeField(blank=True, null=True)),
                ('asset_code', models.CharField(blank=True, max_length=100, null=True)),
                ('asset_group', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='energy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('water_consumption', models.CharField(max_length=50)),
                ('cng_consumption', models.CharField(max_length=50)),
                ('electricity_consumption', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('week_of_month', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='energy_trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=50)),
                ('water_monthly', models.CharField(max_length=50)),
                ('cng_monthly', models.CharField(max_length=50)),
                ('electricity_monthly', models.CharField(max_length=50)),
                ('month_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='unrealesed_work_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_description', models.CharField(max_length=255)),
                ('wo_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wo_status', models.CharField(max_length=50)),
                ('wo_created_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('wo_description', models.CharField(max_length=255)),
                ('resource', models.CharField(max_length=100)),
                ('wo_type', models.CharField(max_length=50)),
                ('wo_status', models.CharField(max_length=50)),
                ('wo_created_date', models.DateTimeField()),
                ('wr_requestor', models.CharField(max_length=100)),
                ('wo_actual_completion_date', models.DateTimeField()),
                ('actual_duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
                ('version', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('SOP', 'SOP'), ('Manual', 'Manual'), ('Form', 'Form'), ('Specification', 'Specification'), ('Work Instruction', 'Work Instruction')], max_length=50)),
                ('department', models.CharField(choices=[('Engineering', 'Engineering'), ('Quality', 'Quality'), ('Utility', 'Utility'), ('Safety', 'Safety'), ('Production', 'Production')], max_length=100)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Archived', 'Archived')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyInput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('listrik', 'Listrik'), ('air', 'Air'), ('cng', 'CNG')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meter_number', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='energy_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_inputs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('engineer', 'Engineer'), ('utility', 'Utility Team'), ('qac', 'QAC/Compliance'), ('requester', 'Division Req')], max_length=20)),
                ('division', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending')], default='Active', max_length=20)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wr_number', models.CharField(editable=False, max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('asset_number', models.CharField(default='UNKNOWN', max_length=100)),
                ('asset_department', models.CharField(default='EN', max_length=100)),
                ('resource', models.CharField(default='mtc', max_length=100)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('wr_type', models.CharField(choices=[('repair', 'Repair'), ('inspection', 'Inspection'), ('corrective', 'Corrective'), ('modification', 'Modification'), ('routine', 'Routine Check')], max_length=20)),
                ('failure_code', models.CharField(blank=True, max_length=100, null=True)),
                ('failure_cause', models.TextField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('actual_failure_date', models.DateField(blank=True, null=True)),
                ('completion_by_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_review', 'In Review')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_number', models.CharField(editable=False, max_length=100, unique=True)),
                ('wr_number', models.CharField(default='WR-DEFAULT', max_length=100)),
                ('title', models.CharField(default='No title', max_length=255)),
                ('description', models.TextField(default='No description')),
                ('asset_number', models.CharField(default='UNKNOWN', max_length=100)),
                ('asset_department', models.CharField(default='EN', max_length=100)),
                ('asset_group', models.CharField(blank=True, max_length=100, null=True)),
                ('asset_area', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_asset', models.CharField(blank=True, max_length=100, null=True)),
                ('resource', models.CharField(default='EN', max_length=100)),
                ('urgency', models.CharField(default='UNKNOWN', max_length=10)),
                ('wo_type', models.CharField(default='UNKNOWN', max_length=50)),
                ('failure_code', models.CharField(blank=True, max_length=100, null=True)),
                ('failure_cause', models.TextField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('actual_failure_date', models.DateField(blank=True, null=True)),
                ('completion_by_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('unreleased', 'Unreleased'), ('released', 'Released'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='unreleased', max_length=20)),
                ('wo_created_at', models.DateTimeField(auto_now_add=True)),
                ('wo_start_date', models.DateTimeField(blank=True, null=True)),
                ('wo_completion_date', models.DateTimeField(blank=True, null=True)),
                ('actual_duration', models.DurationField(blank=True, null=True)),
                ('engineer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_order', to='engineering_app.workrequest')),
            ],
        ),
    ]
