# Generated by Django 5.2.4 on 2025-07-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engineering_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="division",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
