# Generated by Django 5.2 on 2025-07-28 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineering_app', '0001_initial'),
    ]

    operations = [
    ]
