# Generated by Django 5.2 on 2025-07-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering_app', '0002_auto_20250728_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrequest',
            name='resource',
            field=models.CharField(default='MTC', max_length=100),
        ),
    ]
