# Generated by Django 5.2 on 2025-07-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering_app', '0002_userprofile_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='active_work_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_description', models.CharField(max_length=255)),
                ('wo_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wo_status', models.CharField(max_length=50)),
                ('wo_created_date', models.DateTimeField()),
            ],
        ),
    ]
