# Generated by Django 5.2.1 on 2025-07-25 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engineering_app", "0003_active_work_orders"),
        ("engineering_app", "0003_userprofile_avatar_userprofile_full_name_and_more"),
    ]

    operations = []
