# Generated by Django 5.2.1 on 2025-07-25 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engineering_app", "0004_merge_20250725_0832"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="unrealesed_work_orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wo_description", models.CharField(max_length=255)),
                ("wo_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("wo_status", models.CharField(max_length=50)),
                ("wo_created_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="WorkOrderList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no", models.IntegerField()),
                ("title", models.CharField(max_length=100)),
                ("wo_description", models.CharField(max_length=255)),
                ("resource", models.CharField(max_length=100)),
                ("wo_type", models.CharField(max_length=50)),
                ("wo_status", models.CharField(max_length=50)),
                ("wo_created_date", models.DateTimeField()),
                ("wr_requestor", models.CharField(max_length=100)),
                ("wo_actual_completion_date", models.DateTimeField()),
                ("actual_duration", models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name="WORequesterTwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("wr_number", models.BigIntegerField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("wo_description", models.TextField()),
                ("wr_type", models.CharField(max_length=50)),
                ("wr_request_by_date", models.DateField()),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("week_of_month", models.IntegerField()),
                (
                    "resource",
                    models.CharField(
                        choices=[
                            ("MTC", "Maintenance"),
                            ("CAL", "Calibration"),
                            ("UTY", "Utility"),
                        ],
                        max_length=10,
                    ),
                ),
                ("asset_number", models.CharField(max_length=50)),
                (
                    "asset_department",
                    models.CharField(
                        choices=[
                            ("EN", "Engineering"),
                            ("GA", "General Affairs"),
                            ("PD", "Production"),
                            ("QA", "Quality Assurance"),
                            ("QC", "Quality Control"),
                            ("RD", "Research & Development"),
                            ("WH", "Warehouse"),
                        ],
                        max_length=10,
                    ),
                ),
                ("urgency", models.CharField(default="Normal", max_length=50)),
                ("status", models.CharField(default="Pending", max_length=50)),
                (
                    "wr_requestor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wr_number", models.BigIntegerField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("wo_description", models.TextField()),
                ("wr_type", models.CharField(default="Perbaikan", max_length=100)),
                ("resource", models.CharField(max_length=50)),
                ("asset_number", models.CharField(max_length=50)),
                ("asset_department", models.CharField(max_length=50)),
                ("wr_request_by_date", models.DateField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("week_of_month", models.IntegerField()),
                ("status", models.CharField(default="Pending", max_length=50)),
                ("urgency", models.CharField(default="Normal", max_length=50)),
                (
                    "wr_requestor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
