# Generated by Django 5.2 on 2025-07-26 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering_app', '0004_merge_20250726_1135'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_number', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_completion', models.DateTimeField(blank=True, null=True)),
                ('actual_failure_date', models.DateTimeField(blank=True, null=True)),
                ('asset_code', models.CharField(blank=True, max_length=100, null=True)),
                ('asset_group', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='energy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(max_length=50)),
                ('water_consumption', models.CharField(max_length=50)),
                ('cng_consumption', models.CharField(max_length=50)),
                ('electricity_consumption', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('week_of_month', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='energy_trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=50)),
                ('water_monthly', models.CharField(max_length=50)),
                ('cng_monthly', models.CharField(max_length=50)),
                ('electricity_monthly', models.CharField(max_length=50)),
                ('month_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='unrealesed_work_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_description', models.CharField(max_length=255)),
                ('wo_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wo_status', models.CharField(max_length=50)),
                ('wo_created_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('wo_description', models.CharField(max_length=255)),
                ('resource', models.CharField(max_length=100)),
                ('wo_type', models.CharField(max_length=50)),
                ('wo_status', models.CharField(max_length=50)),
                ('wo_created_date', models.DateTimeField()),
                ('wr_requestor', models.CharField(max_length=100)),
                ('wo_actual_completion_date', models.DateTimeField()),
                ('actual_duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wr_number', models.CharField(editable=False, max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('asset_number', models.CharField(max_length=100)),
                ('asset_department', models.CharField(max_length=100)),
                ('resource', models.CharField(max_length=100)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('wr_type', models.CharField(choices=[('repair', 'Repair'), ('inspection', 'Inspection'), ('corrective', 'Corrective'), ('modification', 'Modification'), ('routine', 'Routine Check')], max_length=20)),
                ('failure_code', models.CharField(blank=True, max_length=100, null=True)),
                ('failure_cause', models.TextField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('actual_failure_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_review', 'In Review')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
