# Generated by Django 5.2 on 2025-07-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering_app', '0005_analytics_energy_energy_trend_unrealesed_work_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrequest',
            name='asset_activity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='asset_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='asset_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='parent_asset',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
