# Generated by Django 5.2.1 on 2025-07-26 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "engineering_app",
            "0005_unrealesed_work_orders_workorderlist_worequestertwo_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="workrequest",
            old_name="submitted_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="workrequest",
            old_name="wo_description",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="workrequest",
            name="month",
        ),
        migrations.RemoveField(
            model_name="workrequest",
            name="week_of_month",
        ),
        migrations.RemoveField(
            model_name="workrequest",
            name="wr_request_by_date",
        ),
        migrations.RemoveField(
            model_name="workrequest",
            name="wr_requestor",
        ),
        migrations.RemoveField(
            model_name="workrequest",
            name="year",
        ),
        migrations.AddField(
            model_name="workrequest",
            name="actual_failure_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workrequest",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workrequest",
            name="failure_cause",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workrequest",
            name="failure_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="workrequest",
            name="requested_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_requests",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workrequest",
            name="resolution",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workrequest",
            name="asset_department",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="workrequest",
            name="asset_number",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="workrequest",
            name="resource",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="workrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("in_review", "In Review"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workrequest",
            name="urgency",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="workrequest",
            name="wr_number",
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="workrequest",
            name="wr_type",
            field=models.CharField(
                choices=[
                    ("repair", "Repair"),
                    ("inspection", "Inspection"),
                    ("corrective", "Corrective"),
                    ("modification", "Modification"),
                    ("routine", "Routine Check"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="WORequesterTwo",
        ),
    ]
