# Generated by Django 5.2 on 2025-07-27 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering_app', '0006_workrequest_asset_activity_workrequest_asset_area_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workrequest',
            old_name='wr_type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='workrequest',
            name='completion_by_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_number', models.CharField(editable=False, max_length=100, unique=True)),
                ('wo_status', models.CharField(choices=[('unreleased', 'Unreleased'), ('released', 'Released'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='unreleased', max_length=20)),
                ('wo_created_at', models.DateTimeField(auto_now_add=True)),
                ('wo_start_date', models.DateTimeField(blank=True, null=True)),
                ('wo_completion_date', models.DateTimeField(blank=True, null=True)),
                ('actual_duration', models.DurationField(blank=True, null=True)),
                ('work_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_order', to='engineering_app.workrequest')),
            ],
        ),
    ]
