# Generated by Django 5.2.1 on 2025-07-26 08:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engineering_app", "0006_rename_submitted_at_workrequest_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnergyInput",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("listrik", "Listrik"),
                            ("air", "Air"),
                            ("cng", "CNG"),
                        ],
                        max_length=10,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("meter_number", models.CharField(max_length=100)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="energy_photos/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="energy_inputs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
