# Generated by Django 5.2.1 on 2025-07-27 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "engineering_app",
            "0005_analytics_energy_energy_trend_unrealesed_work_orders_and_more",
        ),
        ("engineering_app", "0007_energyinput"),
    ]

    operations = []
