# Generated by Django 5.2.1 on 2025-07-27 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engineering_app", "0008_merge_20250727_1123"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Inactive", "Inactive"),
                    ("Pending", "Pending"),
                ],
                default="Active",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_url", models.URLField()),
                ("version", models.CharField(max_length=20)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SOP", "SOP"),
                            ("Manual", "Manual"),
                            ("Form", "Form"),
                            ("Specification", "Specification"),
                            ("Work Instruction", "Work Instruction"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Engineering", "Engineering"),
                            ("Quality", "Quality"),
                            ("Utility", "Utility"),
                            ("Safety", "Safety"),
                            ("Production", "Production"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Active", "Active"),
                            ("Archived", "Archived"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
