# Generated by Django 5.2 on 2025-07-29 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering_app', '0008_merge_20250727_1123'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workrequest',
            name='completion_by_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='energy',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='asset_department',
            field=models.CharField(default='EN', max_length=100),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='asset_number',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='resource',
            field=models.CharField(default='MTC', max_length=100),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
                ('version', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('SOP', 'SOP'), ('Manual', 'Manual'), ('Form', 'Form'), ('Specification', 'Specification'), ('Work Instruction', 'Work Instruction')], max_length=50)),
                ('department', models.CharField(choices=[('Engineering', 'Engineering'), ('Quality', 'Quality'), ('Utility', 'Utility'), ('Safety', 'Safety'), ('Production', 'Production')], max_length=100)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Archived', 'Archived')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_number', models.CharField(editable=False, max_length=100, unique=True)),
                ('wr_number', models.CharField(default='WR-DEFAULT', max_length=100)),
                ('title', models.CharField(default='No title', max_length=255)),
                ('description', models.TextField(default='No description')),
                ('asset_number', models.CharField(default='UNKNOWN', max_length=100)),
                ('asset_department', models.CharField(default='EN', max_length=100)),
                ('asset_group', models.CharField(blank=True, max_length=100, null=True)),
                ('asset_area', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_asset', models.CharField(blank=True, max_length=100, null=True)),
                ('resource', models.CharField(default='EN', max_length=100)),
                ('urgency', models.CharField(default='UNKNOWN', max_length=10)),
                ('wo_type', models.CharField(default='UNKNOWN', max_length=50)),
                ('failure_code', models.CharField(blank=True, max_length=100, null=True)),
                ('failure_cause', models.TextField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('actual_failure_date', models.DateField(blank=True, null=True)),
                ('completion_by_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('unreleased', 'Unreleased'), ('released', 'Released'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='unreleased', max_length=20)),
                ('wo_created_at', models.DateTimeField(auto_now_add=True)),
                ('wo_start_date', models.DateTimeField(blank=True, null=True)),
                ('wo_completion_date', models.DateTimeField(blank=True, null=True)),
                ('actual_duration', models.DurationField(blank=True, null=True)),
                ('engineer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_order', to='engineering_app.workrequest')),
            ],
        ),
    ]
