# Generated by Django 5.2 on 2025-07-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering_app', '0008_rename_type_workrequest_wr_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='asset_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='asset_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workorder',
            name='failure_cause',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='failure_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='parent_asset',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='resolution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
