# Generated by Django 5.2.1 on 2025-07-28 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engineering_app", "0009_alter_userprofile_status_document"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="status",
        ),
    ]
