# Generated by Django 5.2 on 2025-07-29 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering_app', '0009_workrequest_completion_by_date_alter_energy_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='asset_activity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='pm_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='set_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='work_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_order', to='engineering_app.workrequest'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='wr_number',
            field=models.CharField(blank=True, default='WR-DEFAULT', max_length=100, null=True),
        ),
    ]
