# Generated by Django 5.2 on 2025-07-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering_app', '0010_workorder_asset_activity_workorder_pm_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrequest',
            name='wr_type',
            field=models.CharField(choices=[('repair', 'Repair'), ('calibration', 'Calibration'), ('evaluation', 'Evaluation'), ('planned', 'Planned Maintenance'), ('predictive', 'Predictive Maintenance'), ('preventive', 'Preventive Maintenance'), ('other', 'Other')], max_length=20),
        ),
    ]
