# Generated by Django 5.2 on 2025-07-27 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering_app', '0011_rename_wo_status_workorder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='work_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_order', to='engineering_app.workrequest'),
        ),
    ]
