# Generated by Django 5.2 on 2025-07-31 01:34

from django.db import migrations, models, connection

def skip_if_column_exists(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='engineering_app_document' AND column_name='size';
        """)
        if cursor.fetchone() is None:
            cursor.execute('ALTER TABLE engineering_app_document ADD COLUMN size bigint;')

class Migration(migrations.Migration):

    dependencies = [
        ('engineering_app', '0012_audittrail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='status',
        ),
        migrations.RunPython(skip_if_column_exists),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
