# Generated by Django 5.2 on 2025-07-31 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering_app', '0013_remove_document_status_document_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_review', 'In Review'), ('planned', 'Planned')], default='pending', max_length=20),
        ),
    ]
