# Generated by Django 5.2 on 2025-07-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering_app', '0013_workrequest_asset_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
