# Generated by Django 5.2 on 2025-07-27 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineering_app', '0007_rename_wr_type_workrequest_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workrequest',
            old_name='type',
            new_name='wr_type',
        ),
        migrations.RemoveField(
            model_name='workrequest',
            name='asset_activity',
        ),
        migrations.RemoveField(
            model_name='workrequest',
            name='asset_area',
        ),
        migrations.RemoveField(
            model_name='workrequest',
            name='asset_department',
        ),
        migrations.RemoveField(
            model_name='workrequest',
            name='asset_group',
        ),
        migrations.RemoveField(
            model_name='workrequest',
            name='asset_number',
        ),
        migrations.RemoveField(
            model_name='workrequest',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='workrequest',
            name='parent_asset',
        ),
        migrations.RemoveField(
            model_name='workrequest',
            name='resource',
        ),
    ]
