# Generated by Django 5.2 on 2025-07-27 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering_app', '0009_workorder_asset_area_workorder_asset_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='cost',
        ),
        migrations.AddField(
            model_name='workorder',
            name='actual_failure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='asset_department',
            field=models.CharField(default='EN', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='asset_number',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='completion_by_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='engineer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorder',
            name='resource',
            field=models.CharField(default='EN', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='title',
            field=models.CharField(default='No title', max_length=255),
        ),
        migrations.AddField(
            model_name='workorder',
            name='urgency',
            field=models.CharField(default='UNKNOWN', max_length=10),
        ),
        migrations.AddField(
            model_name='workorder',
            name='wo_type',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
        migrations.AddField(
            model_name='workorder',
            name='wr_number',
            field=models.CharField(default='WR-DEFAULT', max_length=100),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='work_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='engineering_app.workrequest'),
        ),
    ]
