# Generated by Django 5.2 on 2025-07-27 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineering_app', '0010_remove_workorder_cost_workorder_actual_failure_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='wo_status',
            new_name='status',
        ),
    ]
