# Generated by Django 5.2 on 2025-07-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering_app', '0012_workorder_requester_alter_workorder_work_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrequest',
            name='asset_department',
            field=models.CharField(default='EN', max_length=100),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='asset_number',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
    ]
